name: CI

on:
  push:
    branches:
      - development
      - __release-*
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12.14.1]
        os: [macos-10.15]
        include:
          - os: macos-10.15
            friendlyName: macOS
    timeout-minutes: 40
    steps:
      - name: Get repository name.
        run: echo ::set-env name=REPO_NAME::${GITHUB_REPOSITORY##*/}

      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install and build dependencies
        run: yarn
      - name: Build production app
        run: yarn build:prod
        env:
          DESKTOP_OAUTH_CLIENT_ID: ${{ secrets.DESKTOP_OAUTH_CLIENT_ID }}
          DESKTOP_OAUTH_CLIENT_SECRET:
            ${{ secrets.DESKTOP_OAUTH_CLIENT_SECRET }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DESKTOPBOT_TOKEN: ${{ secrets.DESKTOPBOT_TOKEN }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: List artiffacts
        run: ls -l ${{ env.REPO_NAME }}/dist/GitLab (wrk)-darwin-x64/
      - uses: actions/upload-artifact@master
        name: Upload artifact.
        with:
          name: Gitlab (wrk).app
          path: ${{ env.REPO_NAME }}/dist/GitLab (wrk)-darwin-x64/
